/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         12000000U  /*!< Board xtal0 frequency in Hz */
#define BOARD_XTAL32K_CLK_HZ                          32768U  /*!< Board xtal32K frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockFRO12M **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFRO12M_CORE_CLOCK           12000000U  /*!< Core clock frequency: 12000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFRO12M_ADC_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_ASYNCAPB_CLOCK          0UL
#define BOARD_BOOTCLOCKFRO12M_CLKOUT_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_DMIC_CLOCK              0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM0_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM1_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM2_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM3_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM4_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM5_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM6_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM7_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOMS_CLK32K_CLOCK     0UL
#define BOARD_BOOTCLOCKFRO12M_MASTER_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_PLL_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_SYSTICK_CLOCK           0UL
#define BOARD_BOOTCLOCKFRO12M_SYSTEM_CLOCK            12000000UL
#define BOARD_BOOTCLOCKFRO12M_TRACE_CLOCK             0UL
#define BOARD_BOOTCLOCKFRO12M_USB_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_WDT_CLOCK               0UL

/*******************************************************************************
 * API for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFRO12M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF48M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFROHF48M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFROHF48M_CORE_CLOCK         48000000U  /*!< Core clock frequency: 48000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFROHF48M_ADC_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_ASYNCAPB_CLOCK        0UL
#define BOARD_BOOTCLOCKFROHF48M_CLKOUT_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_DMIC_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM0_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM1_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM2_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM3_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM4_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM5_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM6_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM7_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOMS_CLK32K_CLOCK   0UL
#define BOARD_BOOTCLOCKFROHF48M_MASTER_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_PLL_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_SYSTICK_CLOCK         0UL
#define BOARD_BOOTCLOCKFROHF48M_SYSTEM_CLOCK          48000000UL
#define BOARD_BOOTCLOCKFROHF48M_TRACE_CLOCK           0UL
#define BOARD_BOOTCLOCKFROHF48M_USB_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_WDT_CLOCK             0UL

/*******************************************************************************
 * API for BOARD_BootClockFROHF48M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFROHF48M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF96M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFROHF96M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFROHF96M_CORE_CLOCK         96000000U  /*!< Core clock frequency: 96000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFROHF96M_ADC_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_ASYNCAPB_CLOCK        0UL
#define BOARD_BOOTCLOCKFROHF96M_CLKOUT_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_DMIC_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM0_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM1_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM2_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM3_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM4_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM5_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM6_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM7_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOMS_CLK32K_CLOCK   0UL
#define BOARD_BOOTCLOCKFROHF96M_MASTER_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_PLL_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_SYSTICK_CLOCK         0UL
#define BOARD_BOOTCLOCKFROHF96M_SYSTEM_CLOCK          96000000UL
#define BOARD_BOOTCLOCKFROHF96M_TRACE_CLOCK           0UL
#define BOARD_BOOTCLOCKFROHF96M_USB_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_WDT_CLOCK             0UL

/*******************************************************************************
 * API for BOARD_BootClockFROHF96M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFROHF96M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL150M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL150M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL150M_CORE_CLOCK         150000000U  /*!< Core clock frequency: 150000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL150M_ADC_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL150M_ASYNCAPB_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL150M_CLKOUT_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_DMIC_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM0_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM1_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM2_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM3_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM4_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM5_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM6_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOM7_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_FXCOMS_CLK32K_CLOCK    0UL
#define BOARD_BOOTCLOCKPLL150M_MASTER_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL150M_PLL_CLOCK              150000000UL
#define BOARD_BOOTCLOCKPLL150M_SYSTICK_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL150M_SYSTEM_CLOCK           150000000UL
#define BOARD_BOOTCLOCKPLL150M_TRACE_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL150M_USB_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL150M_WDT_CLOCK              0UL

/*******************************************************************************
 * API for BOARD_BootClockPLL150M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL150M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

